# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from django_socio_grpc.tests.echo import echo_pb2 as django__socio__grpc_dot_tests_dot_echo_dot_echo__pb2


class EchoServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.handler = channel.unary_unary(
                '/test.v1.EchoService/handler',
                request_serializer=django__socio__grpc_dot_tests_dot_echo_dot_echo__pb2.EchoRequest.SerializeToString,
                response_deserializer=django__socio__grpc_dot_tests_dot_echo_dot_echo__pb2.EchoResponse.FromString,
                )


class EchoServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def handler(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EchoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'handler': grpc.unary_unary_rpc_method_handler(
                    servicer.handler,
                    request_deserializer=django__socio__grpc_dot_tests_dot_echo_dot_echo__pb2.EchoRequest.FromString,
                    response_serializer=django__socio__grpc_dot_tests_dot_echo_dot_echo__pb2.EchoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'test.v1.EchoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class EchoService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def handler(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/test.v1.EchoService/handler',
            django__socio__grpc_dot_tests_dot_echo_dot_echo__pb2.EchoRequest.SerializeToString,
            django__socio__grpc_dot_tests_dot_echo_dot_echo__pb2.EchoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
