# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: django_socio_grpc/tests/filter_test/filter_test.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
    name="django_socio_grpc/tests/filter_test/filter_test.proto",
    package="filtertest",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n5django_socio_grpc/tests/filter_test/filter_test.proto\x12\nfiltertest\x1a\x1bgoogle/protobuf/empty.proto"5\n\nFilterTest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0c\n\x04text\x18\x03 \x01(\t"\x17\n\x15\x46ilterTestListRequest"\'\n\x19\x46ilterTestRetrieveRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x32\xdf\x02\n\x14\x46ilterTestController\x12\x45\n\x04List\x12!.filtertest.FilterTestListRequest\x1a\x16.filtertest.FilterTest"\x00\x30\x01\x12:\n\x06\x43reate\x12\x16.filtertest.FilterTest\x1a\x16.filtertest.FilterTest"\x00\x12K\n\x08Retrieve\x12%.filtertest.FilterTestRetrieveRequest\x1a\x16.filtertest.FilterTest"\x00\x12:\n\x06Update\x12\x16.filtertest.FilterTest\x1a\x16.filtertest.FilterTest"\x00\x12;\n\x07\x44\x65stroy\x12\x16.filtertest.FilterTest\x1a\x16.google.protobuf.Empty"\x00\x62\x06proto3',
    dependencies=[
        google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,
    ],
)


_FILTERTEST = _descriptor.Descriptor(
    name="FilterTest",
    full_name="filtertest.FilterTest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="id",
            full_name="filtertest.FilterTest.id",
            index=0,
            number=1,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="title",
            full_name="filtertest.FilterTest.title",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="text",
            full_name="filtertest.FilterTest.text",
            index=2,
            number=3,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=98,
    serialized_end=151,
)


_FILTERTESTLISTREQUEST = _descriptor.Descriptor(
    name="FilterTestListRequest",
    full_name="filtertest.FilterTestListRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=153,
    serialized_end=176,
)


_FILTERTESTRETRIEVEREQUEST = _descriptor.Descriptor(
    name="FilterTestRetrieveRequest",
    full_name="filtertest.FilterTestRetrieveRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="id",
            full_name="filtertest.FilterTestRetrieveRequest.id",
            index=0,
            number=1,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=178,
    serialized_end=217,
)

DESCRIPTOR.message_types_by_name["FilterTest"] = _FILTERTEST
DESCRIPTOR.message_types_by_name["FilterTestListRequest"] = _FILTERTESTLISTREQUEST
DESCRIPTOR.message_types_by_name["FilterTestRetrieveRequest"] = _FILTERTESTRETRIEVEREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FilterTest = _reflection.GeneratedProtocolMessageType(
    "FilterTest",
    (_message.Message,),
    {
        "DESCRIPTOR": _FILTERTEST,
        "__module__": "django_socio_grpc.tests.filter_test.filter_test_pb2"
        # @@protoc_insertion_point(class_scope:filtertest.FilterTest)
    },
)
_sym_db.RegisterMessage(FilterTest)

FilterTestListRequest = _reflection.GeneratedProtocolMessageType(
    "FilterTestListRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _FILTERTESTLISTREQUEST,
        "__module__": "django_socio_grpc.tests.filter_test.filter_test_pb2"
        # @@protoc_insertion_point(class_scope:filtertest.FilterTestListRequest)
    },
)
_sym_db.RegisterMessage(FilterTestListRequest)

FilterTestRetrieveRequest = _reflection.GeneratedProtocolMessageType(
    "FilterTestRetrieveRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _FILTERTESTRETRIEVEREQUEST,
        "__module__": "django_socio_grpc.tests.filter_test.filter_test_pb2"
        # @@protoc_insertion_point(class_scope:filtertest.FilterTestRetrieveRequest)
    },
)
_sym_db.RegisterMessage(FilterTestRetrieveRequest)


_FILTERTESTCONTROLLER = _descriptor.ServiceDescriptor(
    name="FilterTestController",
    full_name="filtertest.FilterTestController",
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_start=220,
    serialized_end=571,
    methods=[
        _descriptor.MethodDescriptor(
            name="List",
            full_name="filtertest.FilterTestController.List",
            index=0,
            containing_service=None,
            input_type=_FILTERTESTLISTREQUEST,
            output_type=_FILTERTEST,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="Create",
            full_name="filtertest.FilterTestController.Create",
            index=1,
            containing_service=None,
            input_type=_FILTERTEST,
            output_type=_FILTERTEST,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="Retrieve",
            full_name="filtertest.FilterTestController.Retrieve",
            index=2,
            containing_service=None,
            input_type=_FILTERTESTRETRIEVEREQUEST,
            output_type=_FILTERTEST,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="Update",
            full_name="filtertest.FilterTestController.Update",
            index=3,
            containing_service=None,
            input_type=_FILTERTEST,
            output_type=_FILTERTEST,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="Destroy",
            full_name="filtertest.FilterTestController.Destroy",
            index=4,
            containing_service=None,
            input_type=_FILTERTEST,
            output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
    ],
)
_sym_db.RegisterServiceDescriptor(_FILTERTESTCONTROLLER)

DESCRIPTOR.services_by_name["FilterTestController"] = _FILTERTESTCONTROLLER

# @@protoc_insertion_point(module_scope)
