# Generated by Django 2.2 on 2021-03-25 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='grcpErrorCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True)),
                ('modified', models.DateTimeField(blank=True)),
                ('code', models.IntegerField(default=0)),
                ('status', models.CharField(db_index=True, max_length=40)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='gRPC Notes')),
            ],
            options={
                'verbose_name': 'GRPC ERROR CODE',
                'verbose_name_plural': 'GRPC ERRORS CODES',
            },
        ),
        migrations.CreateModel(
            name='socioGrpcErrors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True)),
                ('modified', models.DateTimeField(blank=True)),
                ('call_type', models.IntegerField(choices=[(1, 'LIST'), (2, 'GET')], default=0)),
            ],
            options={
                'verbose_name': 'GRPC ERROR HANDLER',
                'verbose_name_plural': 'GRPC ERRORS HANDLER',
            },
        ),
    ]
