# Generated by Django 2.2 on 2021-03-26 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_grpc_framework', '0004_auto_20210326_0101'),
    ]

    operations = [
        migrations.CreateModel(
            name='grcpMicroServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True)),
                ('modified', models.DateTimeField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('service', models.CharField(db_index=True, max_length=40, verbose_name='Service Name')),
                ('category', models.IntegerField(choices=[(1, 'SOCOTEC'), (2, 'GOOGLE')], default=1, verbose_name='Services Category')),
                ('description', models.TextField(blank=True, null=True, verbose_name='gRPC Notes')),
                ('count', models.BigIntegerField(default=0, verbose_name='Count Access')),
            ],
            options={
                'verbose_name': 'GRPC SERVICE REFERENCE',
                'verbose_name_plural': 'GRPC SERVICES REFERENCES',
            },
        ),
    ]
