# Generated by Django 2.2 on 2021-03-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_grpc_framework', '0005_grcpmicroservices'),
    ]

    operations = [
        migrations.AddField(
            model_name='grcperrorcode',
            name='category',
            field=models.IntegerField(choices=[(1, 'Critical'), (2, 'Warning')], default=1, verbose_name='Error Type'),
        ),
    ]
