# Generated by Django 2.2 on 2021-03-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_grpc_framework', '0006_grcperrorcode_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='grcpDataBases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True)),
                ('modified', models.DateTimeField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('database', models.CharField(db_index=True, max_length=40)),
                ('description', models.TextField(blank=True, null=True, verbose_name='gRPC Notes')),
            ],
            options={
                'verbose_name': 'GRPC DATABASE',
                'verbose_name_plural': 'GRPC DATABASES',
            },
        ),
    ]
