# Generated by Django 2.2 on 2021-03-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_grpc_framework', '0007_grcpdatabases'),
    ]

    operations = [
        migrations.AddField(
            model_name='grcpdatabases',
            name='django',
            field=models.CharField(db_index=True, default='', max_length=40, verbose_name='Django Application'),
        ),
        migrations.AlterField(
            model_name='grcpdatabases',
            name='database',
            field=models.CharField(db_index=True, default='', max_length=40, verbose_name='Table SQL'),
        ),
    ]
