# Generated by Django 2.2 on 2021-03-26 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_grpc_framework', '0008_auto_20210326_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='grcpdatabases',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_grpc_framework.grcpMicroServices', verbose_name='Socotec Microservice'),
        ),
    ]
