# Generated by Django 2.2 on 2021-03-27 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_grpc_framework', '0011_auto_20210327_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='grcpProtoBufFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True)),
                ('modified', models.DateTimeField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('field', models.CharField(db_index=True, default='', max_length=50, verbose_name='Protobuf Field')),
                ('is_query', models.BooleanField(default=False)),
                ('field_sequence', models.IntegerField(default=1, verbose_name='Field Sequence')),
                ('query_sequence', models.IntegerField(default=1, verbose_name='Query Sequence')),
                ('database', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_grpc_framework.grcpDataBases', verbose_name='Microservice Protobuf')),
                ('protobuf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_grpc_framework.grcpProtoBuf', verbose_name='Microservice Database')),
            ],
            options={
                'verbose_name': 'GRPC PROTOBUF FIELD',
                'verbose_name_plural': 'GRPC PROTOBUF FIELDS',
            },
        ),
    ]
