# Generated by Django 2.2 on 2021-03-28 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_grpc_framework', '0012_grcpprotobuffields'),
    ]

    operations = [
        migrations.AddField(
            model_name='grcpmicroservices',
            name='directory',
            field=models.CharField(db_index=True, default=models.CharField(db_index=True, max_length=40, verbose_name='Service Name'), max_length=60, verbose_name='Service Directory'),
        ),
        migrations.AlterField(
            model_name='grcpprotobuffields',
            name='database',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_grpc_framework.grcpDataBases', verbose_name='Microservice Database'),
        ),
        migrations.AlterField(
            model_name='grcpprotobuffields',
            name='protobuf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_grpc_framework.grcpProtoBuf', verbose_name='Microservice Protobuf'),
        ),
    ]
