# Generated by Django 2.2 on 2021-03-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_grpc_framework', '0013_auto_20210328_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grcpmicroservices',
            name='directory',
            field=models.CharField(db_index=True, max_length=60, verbose_name='Service Directory'),
        ),
    ]
