# Generated by Django 2.2 on 2021-03-28 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_grpc_framework', '0014_auto_20210328_1501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sociogrpcerrors',
            old_name='call_type',
            new_name='method',
        ),
    ]
