# Generated by Django 2.2 on 2021-03-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_grpc_framework', '0018_sociogrpcerrors_elapse'),
    ]

    operations = [
        migrations.AddField(
            model_name='grcpmicroservices',
            name='isInput',
            field=models.BooleanField(default=False, verbose_name='Input Required'),
        ),
        migrations.AddField(
            model_name='grcpmicroservices',
            name='result',
            field=models.IntegerField(choices=[(1, 'ARRAY'), (2, 'SINGLE')], default=1, verbose_name='Result Type'),
        ),
        migrations.AlterField(
            model_name='sociogrpcerrors',
            name='elapse',
            field=models.FloatField(default=0.0, verbose_name='Elapse Time (sec)'),
        ),
    ]
