# Generated by Django 2.2 on 2021-03-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_grpc_framework', '0019_auto_20210328_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='grcpmicroservices',
            name='error',
            field=models.BigIntegerField(default=0, verbose_name='Count Errors'),
        ),
    ]
