# Generated by Django 2.2 on 2021-03-28 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_grpc_framework', '0022_grpclogging_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='grpclogging',
            name='CQRS',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grpclogging',
            name='EventStore',
            field=models.BooleanField(default=False),
        ),
    ]
