# Generated by Django 2.2 on 2021-03-28 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_grpc_framework', '0024_auto_20210328_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='grpcMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True)),
                ('modified', models.DateTimeField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('method', models.CharField(choices=[('array', 'Array'), ('get', 'Single')], default='array', max_length=40)),
                ('database', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_grpc_framework.grcpDataBases', verbose_name='Database Microservice')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_grpc_framework.grcpMicroServices', verbose_name='Socotec Microservice')),
            ],
            options={
                'verbose_name': 'GRPC SERVICE METHOD',
                'verbose_name_plural': 'GRPC SERVICES METHODS',
            },
        ),
    ]
