# Generated by Django 2.2 on 2021-03-28 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_grpc_framework', '0025_grpcmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='grpcmethod',
            name='result',
            field=models.CharField(choices=[('array', 'Array'), ('get', 'Single')], default='array', max_length=40),
        ),
        migrations.AlterField(
            model_name='grpcmethod',
            name='method',
            field=models.CharField(choices=[('list', 'List'), ('create', 'Create'), ('retrieve', 'Retrieve'), ('update', 'Update'), ('destroy', 'Destroy')], default='list', max_length=40),
        ),
    ]
