# Generated by Django 2.2 on 2021-03-28 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_grpc_framework', '0026_auto_20210328_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='grpcmethod',
            name='is_update',
            field=models.BooleanField(default=False, verbose_name='Updade process'),
        ),
    ]
