# Generated by Django 2.2 on 2021-03-28 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_grpc_framework', '0027_grpcmethod_is_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='grpcmethod',
            name='input',
            field=models.CharField(choices=[('', 'N/A'), ('arg', 'Args')], default='array', max_length=40),
        ),
    ]
