# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: snippets.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='snippets.proto',
  package='snippets',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0esnippets.proto\x12\x08snippets\x1a\x1cgoogle/protobuf/struct.proto\"U\n\x0eNullableString\x12\x0f\n\x05value\x18\x01 \x01(\tH\x00\x12*\n\x04null\x18\x02 \x01(\x0e\x32\x1a.google.protobuf.NullValueH\x00\x42\x06\n\x04kind\"P\n\x07Snippet\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12*\n\x08language\x18\x03 \x01(\x0b\x32\x18.snippets.NullableString2E\n\x11SnippetController\x12\x30\n\x06Update\x12\x11.snippets.Snippet\x1a\x11.snippets.Snippet\"\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_struct__pb2.DESCRIPTOR,])




_NULLABLESTRING = _descriptor.Descriptor(
  name='NullableString',
  full_name='snippets.NullableString',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='snippets.NullableString.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='null', full_name='snippets.NullableString.null', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='kind', full_name='snippets.NullableString.kind',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=58,
  serialized_end=143,
)


_SNIPPET = _descriptor.Descriptor(
  name='Snippet',
  full_name='snippets.Snippet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='snippets.Snippet.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='title', full_name='snippets.Snippet.title', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='language', full_name='snippets.Snippet.language', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=145,
  serialized_end=225,
)

_NULLABLESTRING.fields_by_name['null'].enum_type = google_dot_protobuf_dot_struct__pb2._NULLVALUE
_NULLABLESTRING.oneofs_by_name['kind'].fields.append(
  _NULLABLESTRING.fields_by_name['value'])
_NULLABLESTRING.fields_by_name['value'].containing_oneof = _NULLABLESTRING.oneofs_by_name['kind']
_NULLABLESTRING.oneofs_by_name['kind'].fields.append(
  _NULLABLESTRING.fields_by_name['null'])
_NULLABLESTRING.fields_by_name['null'].containing_oneof = _NULLABLESTRING.oneofs_by_name['kind']
_SNIPPET.fields_by_name['language'].message_type = _NULLABLESTRING
DESCRIPTOR.message_types_by_name['NullableString'] = _NULLABLESTRING
DESCRIPTOR.message_types_by_name['Snippet'] = _SNIPPET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NullableString = _reflection.GeneratedProtocolMessageType('NullableString', (_message.Message,), {
  'DESCRIPTOR' : _NULLABLESTRING,
  '__module__' : 'snippets_pb2'
  # @@protoc_insertion_point(class_scope:snippets.NullableString)
  })
_sym_db.RegisterMessage(NullableString)

Snippet = _reflection.GeneratedProtocolMessageType('Snippet', (_message.Message,), {
  'DESCRIPTOR' : _SNIPPET,
  '__module__' : 'snippets_pb2'
  # @@protoc_insertion_point(class_scope:snippets.Snippet)
  })
_sym_db.RegisterMessage(Snippet)



_SNIPPETCONTROLLER = _descriptor.ServiceDescriptor(
  name='SnippetController',
  full_name='snippets.SnippetController',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=227,
  serialized_end=296,
  methods=[
  _descriptor.MethodDescriptor(
    name='Update',
    full_name='snippets.SnippetController.Update',
    index=0,
    containing_service=None,
    input_type=_SNIPPET,
    output_type=_SNIPPET,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SNIPPETCONTROLLER)

DESCRIPTOR.services_by_name['SnippetController'] = _SNIPPETCONTROLLER

# @@protoc_insertion_point(module_scope)
