# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import snippets_pb2 as snippets__pb2


class SnippetControllerStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Update = channel.unary_unary(
                '/snippets.SnippetController/Update',
                request_serializer=snippets__pb2.Snippet.SerializeToString,
                response_deserializer=snippets__pb2.Snippet.FromString,
                )


class SnippetControllerServicer(object):
    """Missing associated documentation comment in .proto file"""

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SnippetControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=snippets__pb2.Snippet.FromString,
                    response_serializer=snippets__pb2.Snippet.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'snippets.SnippetController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SnippetController(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/snippets.SnippetController/Update',
            snippets__pb2.Snippet.SerializeToString,
            snippets__pb2.Snippet.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
