# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import hrm_pb2 as hrm__pb2


class PersonControllerStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PartialUpdate = channel.unary_unary(
                '/hrm.PersonController/PartialUpdate',
                request_serializer=hrm__pb2.PersonPartialUpdateRequest.SerializeToString,
                response_deserializer=hrm__pb2.Person.FromString,
                )


class PersonControllerServicer(object):
    """Missing associated documentation comment in .proto file"""

    def PartialUpdate(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PersonControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PartialUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.PartialUpdate,
                    request_deserializer=hrm__pb2.PersonPartialUpdateRequest.FromString,
                    response_serializer=hrm__pb2.Person.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hrm.PersonController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PersonController(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def PartialUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hrm.PersonController/PartialUpdate',
            hrm__pb2.PersonPartialUpdateRequest.SerializeToString,
            hrm__pb2.Person.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
