# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: django_socio_grpc/tests/grpc_test_utils/unittest.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="django_socio_grpc/tests/grpc_test_utils/unittest.proto",
    package="unittest",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n6django_socio_grpc/tests/grpc_test_utils/unittest.proto\x12\x08unittest\x1a\x1bgoogle/protobuf/empty.proto"3\n\x08UnitTest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0c\n\x04text\x18\x03 \x01(\t"\x15\n\x13UnitTestListRequest";\n\x14UnitTestListResponse\x12#\n\x07results\x18\x01 \x03(\x0b\x32\x12.unittest.UnitTest"%\n\x17UnitTestRetrieveRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x32\xc3\x02\n\x12UnitTestController\x12G\n\x04List\x12\x1d.unittest.UnitTestListRequest\x1a\x1e.unittest.UnitTestListResponse"\x00\x12\x32\n\x06\x43reate\x12\x12.unittest.UnitTest\x1a\x12.unittest.UnitTest"\x00\x12\x43\n\x08Retrieve\x12!.unittest.UnitTestRetrieveRequest\x1a\x12.unittest.UnitTest"\x00\x12\x32\n\x06Update\x12\x12.unittest.UnitTest\x1a\x12.unittest.UnitTest"\x00\x12\x37\n\x07\x44\x65stroy\x12\x12.unittest.UnitTest\x1a\x16.google.protobuf.Empty"\x00\x62\x06proto3',
    dependencies=[
        google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,
    ],
)


_UNITTEST = _descriptor.Descriptor(
    name="UnitTest",
    full_name="unittest.UnitTest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="id",
            full_name="unittest.UnitTest.id",
            index=0,
            number=1,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="title",
            full_name="unittest.UnitTest.title",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="text",
            full_name="unittest.UnitTest.text",
            index=2,
            number=3,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=97,
    serialized_end=148,
)


_UNITTESTLISTREQUEST = _descriptor.Descriptor(
    name="UnitTestListRequest",
    full_name="unittest.UnitTestListRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=150,
    serialized_end=171,
)


_UNITTESTLISTRESPONSE = _descriptor.Descriptor(
    name="UnitTestListResponse",
    full_name="unittest.UnitTestListResponse",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="results",
            full_name="unittest.UnitTestListResponse.results",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=173,
    serialized_end=232,
)


_UNITTESTRETRIEVEREQUEST = _descriptor.Descriptor(
    name="UnitTestRetrieveRequest",
    full_name="unittest.UnitTestRetrieveRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="id",
            full_name="unittest.UnitTestRetrieveRequest.id",
            index=0,
            number=1,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=234,
    serialized_end=271,
)

_UNITTESTLISTRESPONSE.fields_by_name["results"].message_type = _UNITTEST
DESCRIPTOR.message_types_by_name["UnitTest"] = _UNITTEST
DESCRIPTOR.message_types_by_name["UnitTestListRequest"] = _UNITTESTLISTREQUEST
DESCRIPTOR.message_types_by_name["UnitTestListResponse"] = _UNITTESTLISTRESPONSE
DESCRIPTOR.message_types_by_name["UnitTestRetrieveRequest"] = _UNITTESTRETRIEVEREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UnitTest = _reflection.GeneratedProtocolMessageType(
    "UnitTest",
    (_message.Message,),
    {
        "DESCRIPTOR": _UNITTEST,
        "__module__": "django_socio_grpc.tests.grpc_test_utils.unittest_pb2"
        # @@protoc_insertion_point(class_scope:unittest.UnitTest)
    },
)
_sym_db.RegisterMessage(UnitTest)

UnitTestListRequest = _reflection.GeneratedProtocolMessageType(
    "UnitTestListRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _UNITTESTLISTREQUEST,
        "__module__": "django_socio_grpc.tests.grpc_test_utils.unittest_pb2"
        # @@protoc_insertion_point(class_scope:unittest.UnitTestListRequest)
    },
)
_sym_db.RegisterMessage(UnitTestListRequest)

UnitTestListResponse = _reflection.GeneratedProtocolMessageType(
    "UnitTestListResponse",
    (_message.Message,),
    {
        "DESCRIPTOR": _UNITTESTLISTRESPONSE,
        "__module__": "django_socio_grpc.tests.grpc_test_utils.unittest_pb2"
        # @@protoc_insertion_point(class_scope:unittest.UnitTestListResponse)
    },
)
_sym_db.RegisterMessage(UnitTestListResponse)

UnitTestRetrieveRequest = _reflection.GeneratedProtocolMessageType(
    "UnitTestRetrieveRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _UNITTESTRETRIEVEREQUEST,
        "__module__": "django_socio_grpc.tests.grpc_test_utils.unittest_pb2"
        # @@protoc_insertion_point(class_scope:unittest.UnitTestRetrieveRequest)
    },
)
_sym_db.RegisterMessage(UnitTestRetrieveRequest)


_UNITTESTCONTROLLER = _descriptor.ServiceDescriptor(
    name="UnitTestController",
    full_name="unittest.UnitTestController",
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_start=274,
    serialized_end=597,
    methods=[
        _descriptor.MethodDescriptor(
            name="List",
            full_name="unittest.UnitTestController.List",
            index=0,
            containing_service=None,
            input_type=_UNITTESTLISTREQUEST,
            output_type=_UNITTESTLISTRESPONSE,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="Create",
            full_name="unittest.UnitTestController.Create",
            index=1,
            containing_service=None,
            input_type=_UNITTEST,
            output_type=_UNITTEST,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="Retrieve",
            full_name="unittest.UnitTestController.Retrieve",
            index=2,
            containing_service=None,
            input_type=_UNITTESTRETRIEVEREQUEST,
            output_type=_UNITTEST,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="Update",
            full_name="unittest.UnitTestController.Update",
            index=3,
            containing_service=None,
            input_type=_UNITTEST,
            output_type=_UNITTEST,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="Destroy",
            full_name="unittest.UnitTestController.Destroy",
            index=4,
            containing_service=None,
            input_type=_UNITTEST,
            output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
    ],
)
_sym_db.RegisterServiceDescriptor(_UNITTESTCONTROLLER)

DESCRIPTOR.services_by_name["UnitTestController"] = _UNITTESTCONTROLLER

# @@protoc_insertion_point(module_scope)
