# Generated by Django 2.2 on 2021-03-25 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_grpc_framework', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grcperrorcode',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='grcperrorcode',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sociogrpcerrors',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sociogrpcerrors',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
