# Generated by Django 2.2 on 2021-03-25 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_grpc_framework', '0002_auto_20210326_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='grcperrorcode',
            name='count',
            field=models.BigIntegerField(default=1),
        ),
    ]
