# Generated by Django 3.2 on 2021-04-29 13:24

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fakeapp", "0003_notdisplayedmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpecialFieldsModel",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("meta_datas", models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
