# Generated by Django 3.2 on 2021-04-30 13:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fakeapp", "0004_specialfieldsmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="specialfieldsmodel",
            name="list_datas",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), blank=True, default=list, size=None
            ),
        ),
    ]
