# Generated by Django 3.2 on 2021-05-03 15:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fakeapp", "0006_specialfieldsmodel_this_is_crazy"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportStructEvenInArrayModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "this_is_crazy",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.JSONField(blank=True, default=dict),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="specialfieldsmodel",
            name="this_is_crazy",
        ),
    ]
